'''From a csv of goal captions for each Metaworld task (generated by ChatGPT), 
make a pickle file like raw-captions.pkl that contains goal captions for success videos and negative goal captions for failure videos'''

import pickle
import pandas as pd

# this goal_captions csv was generated using Metaworld task descriptions (Appendix A) and env_dict in the Metaworld github
goal_captions = pd.read_csv('/home/liao0241/video_language_critic/metaworld-goal-captions.csv')
# task_name_mapping = pd.read_csv('/home/liao0241/video_language_critic/metaworld-task-mapping.csv')

pickle_file_path = '/home/liao0241/video_language_critic/data/metaworld/mw40_split/raw-captions-fails-relabeled.pkl'
# doing this on raw-captions-fails-relabeled.pkl which uses relabel_failures.py to give richer task descriptions to failures

with open(pickle_file_path, 'rb') as f:
    data = pickle.load(f)

# Get all video names (keys)
video_names = list(data.keys())

# Generate the new goal description data
goal_description_dict = {}

for video_name in video_names:
    # Extract the task name
    task_name = video_name.split("__")[-1].split("_")[-2]
    if "success" in video_name:
        goal_description = goal_captions['Goal Description'][goal_captions['Task']==task_name].iloc[0]
    elif "fail" in video_name:
        goal_description = goal_captions['Negative Goal Description'][goal_captions['Task']==task_name].iloc[0]
    goal_description_dict[video_name] = [goal_description.split()]  # this is the format the captions in raw-captions.pkl are in

# Save the new dictionary to a .pkl
output_path = '/home/liao0241/video_language_critic/data/metaworld/mw40_split/goal-captions-fails-relabeled.pkl'  # doing this on fails-relabeled.pkl

with open(output_path, 'wb') as f:
    pickle.dump(goal_description_dict, f)